### ISSUE TITLE
Hugo Newsletter Section

### ISSUE THREAD

**Issue by davidsneighbour** [budparr/awesome-hugo#25]
Hi, I just took over the Hugo newsletter at hugonewsletter.com. Would it be ok if I add a permanent section in the footer of the newsletter referring to this awesome list? Or we (meaning, ehm, you) could add your own section to the newsletter where you list new entries in the list?

I want to build the newsletter into a more or less automated little source of "meanwhile/erstwhile/precedently/recently in the Hugoverse"

**Comment by budparr** [comment]
Sounds good to me. I doubt I'd have time to be adding new entries to the newsletter, but I'm quite happy for people to know about and get some use out of the list.
